services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn byteme.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: byteme.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: your-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
