# Generated by Django 5.2 on 2025-04-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('fully_accessible', 'Fully Accessible'), ('mostly_accessible', 'Mostly Accessible'), ('partially_accessible', 'Partially Accessible'), ('limited_accessibility', 'Limited Accessibility')], max_length=50)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='accessibility_levels',
            field=models.ManyToManyField(related_name='locations', to='locations.accessibilitylevel'),
        ),
        migrations.AddField(
            model_name='location',
            name='categories',
            field=models.ManyToManyField(related_name='locations', to='locations.category'),
        ),
    ]
