# Generated by Django 5.2 on 2025-04-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_proposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilitylevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
